backend/modules/system/controllers/MenuController.php
<?php
// +----------------------------------------------------------------------
// | B5Yii2CMF V3.0 [快捷通用基础管理开发平台]
// +----------------------------------------------------------------------
// | Author: 冰舞 <357145480@qq.com>
// +----------------------------------------------------------------------
declare (strict_types = 1);

namespace backend\modules\system\controllers;

use backend\extend\BaseController;
use common\services\system\MenuService;
use backend\extend\traits\CommonAction;
use common\services\system\RoleMenuService;
use common\models\system\Menu;

class MenuController extends BaseController
{
    use CommonAction;
    protected $model = Menu::class;
    protected $validate = true;

    /**
     * 获取菜单列表
     * @return string
     */
    public function actionTree(){
        $root = $this->request->get('root', 0);
        if($this->request->isPost){
            $list = (new MenuService())->getList($root?true:false);
            return $this->success('',$list);
        }else{
            $id = $this->request->get('id', 0);
            return $this->render('',['menu_id'=>$id,'root'=>$root]);
        }
    }

    /**
     * 首页列表默认排序
     * @param array $params
     * @return array
     */
    protected function indexBefore(array $params): array
    {
        $params['orderBy'] = ['parent_id'=>'asc','listsort'=>'asc'];
        return $params;
    }

    /**
     * 添加渲染
     * @return string
     */
    protected function addRender(): string
    {
        return $this->render('',['typeList'=>(new MenuService())->typeList()]);
    }

    /**
     * 编辑渲染
     * @param $info
     * @return string
     */
    protected function editRender($info): string
    {
        if($info['parent_id']){
            $parent = Menu::findOne($info['parent_id']);
            if($parent){
                $info['parent_name'] = $parent['name'];
            }else{
                $info['parent_name'] = '错误：'.$info['parent_id'];
            }
        }else{
            $info['parent_name'] = '顶级菜单';
        }

        return $this->render('',['info'=>$info,'typeList'=>(new MenuService())->typeList()]);
    }
    /**
     * 删除后操作
     * @param array $data
     */
    protected function deleteAfter(array $data): void
    {
        //删除菜单的角色授权
        (new RoleMenuService())->deleteByMenu($data['id']);
    }
}

backend/modules/system/controllers/RoleController.php
<?php
// +----------------------------------------------------------------------
// | B5Yii2CMF V3.0 [快捷通用基础管理开发平台]
// +----------------------------------------------------------------------
// | Author: 冰舞 <357145480@qq.com>
// +----------------------------------------------------------------------
declare (strict_types = 1);

namespace backend\modules\system\controllers;


use backend\extend\BaseController;
use backend\extend\helpers\DataScopeHelper;
use backend\extend\traits\CommonAction;
use common\services\system\AdminRoleService;
use common\services\system\RoleMenuService;
use common\services\system\RoleStructService;
use common\models\system\Role;

class RoleController extends BaseController
{
    use CommonAction;
    protected $model = Role::class;
    protected $validate = true;

    /**
     * 首页渲染
     * @return string
     */
    protected function indexRender(): string
    {
        $root_id = intval($this->app->params['root_role_id']);
        return $this->render('',['root_id'=>$root_id]);
    }

    /**
     * 角色授权
     * @return array|string
     */
    public function actionAuth()
    {
        if ($this->request->isPost) {
            $role_id = $this->request->post('id', 0);
            $treeId = $this->request->post('treeId', '');
            $result = (new RoleMenuService())->update($role_id,$treeId);
            if(!$result){
                return $this->error('授权发生错误');
            }
            return $this->success();
        } else {
            $role_id = $this->request->get('role_id', 0);
            if (!$role_id) return $this->error('参数错误');
            $info = Role::findOne($role_id);
            if (empty($info)) return $this->error('角色信息不存在');
            $menuList = (new RoleMenuService())->getRoleMenuList($role_id);
            return $this->render("", ['info' => $info->toArray(), 'menuList' => implode(',', $menuList)]);
        }
    }

    /**
     * 角色数据权限
     * @return array|string
     */
    public function actionDatascope()
    {
        if($this->request->isPost){
            $role_id = $this->request->post('id', 0);
            if (!$role_id) {
                return $this->error('参数错误');
            }
            $info = Role::findOne($role_id);
            if (empty($info)) {
                return $this->error('角色信息不存在');
            }
            $dataList = DataScopeHelper::typeList();//数据范围列表
            $data_scope = $this->request->post('data_scope','');
            if(!$data_scope || !array_key_exists($data_scope,$dataList)){
                return $this->error('请选择数据范围');
            }
            $treeId = $this->request->post('treeId', '');
            $result = (new RoleStructService())->update($role_id, $data_scope=='8'?$treeId:'');
            if(!$result){
                return $this->error('发生错误了');
            }
            $info->data_scope = $data_scope;
            $result = $info->save(false);
            if($result === false){
                return $this->error('数据保存失败');
            }
            return $this->success();
        }else{
            $role_id = $this->request->get('role_id', 0);
            if (!$role_id) {
                return $this->error('参数错误');
            }
            $info = Role::findOne($role_id);
            if (empty($info)) {
                return $this->error('角色信息不存在');
            }
            $typeList = DataScopeHelper::typeList();//数据范围列表
            $userStruct = (new RoleStructService())->getRoleStructList($role_id);
            return $this->render("", ['info' => $info->toArray(), 'typeList' => $typeList, 'userStruct' => implode(',', $userStruct)]);
        }
    }

    /**
     * 删除前判断
     * @param array $data
     * @return bool|string
     */
    protected function deleteBefore(array $data)
    {
        $root_id = intval($this->app->params['root_role_id']);
        if($data['id'] == $root_id){
            return '默认超管角色无法删除';
        }
        return true;
    }

    /**
     * 删除角色后
     * @param array $data
     */
    protected function deleteAfter(array $data): void
    {
        //删除对应的管理员角色信息
        (new AdminRoleService())->deleteByRole($data['id']);

        //删除对应的权限菜单信息
        (new RoleMenuService())->deleteByRole($data['id']);

        //删除对应角色数据权限信息
        (new RoleStructService())->deleteByRole($data['id']);
    }
}

backend/modules/system/controllers/StructController.php
<?php
// +----------------------------------------------------------------------
// | B5Yii2CMF V3.0 [快捷通用基础管理开发平台]
// +----------------------------------------------------------------------
// | Author: 冰舞 <357145480@qq.com>
// +----------------------------------------------------------------------
declare (strict_types = 1);

namespace backend\modules\system\controllers;

use backend\extend\BaseController;
use backend\extend\traits\CommonAction;
use common\services\system\AdminStructService;
use common\services\system\RoleStructService;
use common\services\system\StructService;
use common\models\system\Struct;

class StructController extends BaseController
{
    use CommonAction;
    protected $model = Struct::class;
    protected $validate = true;

    /**
     * 树形页面
     * @return array|string
     */
    public function actionTree(){
        if ($this->request->isPost) {
            $list = (new StructService())->getList();
            return $this->success('',$list);
        } else {//是否显示父级名称
            $parent = $this->request->get('parent',0);
            $id = $this->request->get('id', 0);
            $ismult = $this->request->get('ismult', 0);
            return $this->render('',['struct_id'=>$id,'parent'=>$parent,'ismult'=>$ismult]);
        }
    }

    /**
     * 首页渲染
     * @return string
     */
    protected function indexRender(): string
    {
        $root_id = intval($this->app->params['root_struct_id']);
        return $this->render('',['root_id'=>$root_id]);
    }

    /**
     * 首页列表默认排序
     * @param array $params
     * @return array
     */
    protected function indexBefore(array $params): array
    {
        $params['orderBy'] = ['parent_id'=>'asc','listsort'=>'asc'];
        return $params;
    }

    /**
     * 添加页渲染
     * @return string
     */
    protected function addRender(): string
    {
        $root_id = intval($this->app->params['root_struct_id']);
        $rootInfo = Struct::findOne($root_id);
        if(!$rootInfo){
            return $this->error("根组织错误，请添加根组织ID：".$root_id);
        }
        return $this->render('',['root_id'=>$root_id,'root_name'=>$rootInfo['name']]);
    }

    /**
     * 编辑页渲染
     * @return string
     */
    protected function editRender(array $info): string
    {
        if($info['parent_id']){
            $info['parent_name'] = implode('-',explode(',',$info['parent_name']));
        }else{
            $info['parent_name'] = '顶级部门';
        }
        $root_id = intval($this->app->params['root_struct_id']);
        return $this->render('',['info'=>$info,'root_id'=>$root_id]);
    }

    /**
     * 添加和编辑保存前 处理 父级信息
     * @param \yii\db\ActiveRecord $model
     * @param string $type
     * @return string
     */
    protected function saveBefore(\yii\db\ActiveRecord $model, string $type)
    {
        if($type == 'add' || $type == 'edit'){
            $root_id = intval($this->app->params['root_struct_id']);
            $parent_id = $model['parent_id']??'';
            if($type == 'add' && !$parent_id){
                return '不能添加顶级部门';
            }
            if($type == 'edit' && $model['id'] == $root_id && $parent_id){
                return '顶级部门不能修改上级部门';
            }
            if($parent_id){
                $parentInfo = Struct::findOne($parent_id);
                if(!$parentInfo){
                    return '上级部门信息不存在';
                }
                $model['parent_name'] = trim($parentInfo['parent_name'].','.$parentInfo['name'],',');
                $model['levels'] = trim($parentInfo['levels'].','.$parentInfo['id'],',');
            }
        }
        return true;
    }

    /**
     * 修改后 进行fullname和levels更新
     * @param \yii\db\ActiveRecord $model
     * @param string $type
     */
    protected function saveAfter(\yii\db\ActiveRecord $model, string $type): void
    {
        if($type == 'edit'){
            (new StructService())->updateExtendField($model['id']);
        }
    }

    /**
     * 删除后操作
     * @param array $data
     */
    protected function deleteAfter(array $data): void
    {
        //删除管理员组织信息
        (new AdminStructService())->deleteByStruct($data['id']);

        //删除角色数据权限信息
        (new RoleStructService())->deleteByStruct($data['id']);
    }
}

backend/modules/system/views/role/add.php
<?php $this->context->layout = '/form';?>

<form class="form-horizontal m" id="form-add">
    <div class="form-group">
        <label class="col-sm-3 control-label is-required">角色名称：</label>
        <div class="col-sm-8">
            <input type="text" name="name" value="" class="form-control" placeholder="请输入角色名称" required autocomplete="off"/>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-3 control-label is-required">角色标识：</label>
        <div class="col-sm-8">
            <input type="text" name="rolekey" value="" class="form-control" placeholder="请输入角色标识" required autocomplete="off"/>
            <span class="help-block m-b-none"><i class="fa fa-info-circle"></i> 角色唯一标识，使用3-20为字母、数字或‘_’组成</span>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-3 control-label is-required">显示顺序：</label>
        <div class="col-sm-8">
            <input type="number" name="listsort" value="0" class="form-control" placeholder="请输入显示顺序" autocomplete="off"/>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-3 control-label is-required">角色状态：</label>
        <div class="col-sm-8">
            <label class="radio-box">
                <input type="radio" name="status" value="0">停用
            </label>
            <label class="radio-box">
                <input type="radio" name="status" value="1" checked>启用
            </label>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-3 control-label ">备注：</label>
        <div class="col-sm-8">
            <textarea name="note" class="form-control" placeholder="请输入备注" rows="3"></textarea>
        </div>
    </div>
</form>

<?php $this->beginBlock('script'); ?>
    <script>
        function submitHandler() {
            if ($.validate.form()) {
                $.operate.save(oasUrl, $('#form-add').serialize());
            }
        }
    </script>
<?php $this->endBlock(); ?>

backend/modules/system/views/role/auth.php
<?php $this->context->layout = '/form';?>

<?= \backend\extend\widgets\Asset::widget(['type'=>['ztree']])?>

<form class="form-horizontal m" id="form-add">
    <div class="form-group">
        <label class="col-sm-3 control-label">角色名称：</label>
        <div class="col-sm-8">
            <div class="form-control-static"><?=$info['name']?></div>
        </div>
    </div>
    <input type="hidden" name="id" value="<?=$info['id']?>">
    <input type="hidden" name="treeId" id="treeId" value="<?=$menuList?>">

    <div class="form-group">
        <label class="col-sm-3 control-label">菜单权限：</label>
        <div class="col-sm-8">
            <label class="check-box">
                <input type="checkbox" value="1" class="treeOpClass">展开/折叠</label>
            <label class="check-box">
                <input type="checkbox" value="2" class="treeOpClass">全选/全不选</label>
            <label class="check-box">
                <input type="checkbox" value="3" class="treeOpClass" checked>父子联动</label>
            <div id="menuTrees" class="ztree ztree-border"></div>
        </div>
    </div>
</form>

<?php $this->beginBlock('script'); ?>
    <script>
        $(function() {
            var options = {
                id: "menuTrees",
                url: "<?=\yii\helpers\Url::toRoute('menu/tree')?>",
                ismult:true,
                childparent:false,
                expandLevel: 1,
                callBack:function (tree) {
                    tree.setting.check.chkboxType = { "Y": "ps", "N": "ps" };
                }
            };
            $.tree.init(options);
            $('input.treeOpClass').on('ifChanged', function(obj){
                var type = $(this).val();
                var checked = obj.currentTarget.checked;
                if (type == 1) {
                    if (checked) {
                        $._tree.expandAll(true);
                    } else {
                        $._tree.expandAll(false);
                    }
                } else if (type == "2") {
                    if (checked) {
                        $._tree.checkAllNodes(true);
                        $.tree.zOnCheck();
                    } else {
                        $._tree.checkAllNodes(false);
                        $.tree.zOnCheck();
                    }
                } else if (type == "3") {
                    if (checked) {
                        $._tree.setting.check.chkboxType = { "Y": "ps", "N": "ps" };
                    } else {
                        $._tree.setting.check.chkboxType = { "Y": "", "N": "" };
                    }
                }
            })
        });
        function submitHandler() {
            $.operate.save(aUrl, $('#form-add').serialize());
        }
    </script>
<?php $this->endBlock(); ?>

backend/modules/system/views/role/datascope.php
<?php $this->context->layout = '/form';?>

<?= \backend\extend\widgets\Asset::widget(['type'=>['ztree']])?>

<form class="form-horizontal m" id="form-add">
    <input type="hidden" name="id" value="<?=$info['id']?>">
    <input type="hidden" name="treeId" id="treeId" value="<?=$userStruct?>">
    <div class="form-group">
        <label class="col-sm-3 control-label">角色名称：</label>
        <div class="col-sm-8">
            <div class="form-control-static"><?=$info['name']?></div>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-3 control-label">角色标识：</label>
        <div class="col-sm-8">
            <div class="form-control-static"><?=$info['rolekey']?></div>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-3 control-label">数据范围：</label>
        <div class="col-sm-8">
            <select name="data_scope" id="data_scope_select" class="form-control">
                <?php foreach ($typeList as $type=>$typeName):?>
                    <option value="<?=$type?>" <?=$info['data_scope']==$type?'selected':''?>><?=$typeName?></option>
                <?php endforeach;?>
            </select>
        </div>
    </div>
    <div class="form-group" id="customData">
        <label class="col-sm-3 control-label">数据权限：</label>
        <div class="col-sm-8">
            <label class="check-box">
                <input type="checkbox" value="1" class="treeOpClass">展开/折叠</label>
            <label class="check-box">
                <input type="checkbox" value="2" class="treeOpClass">全选/全不选</label>
            <label class="check-box">
                <input type="checkbox" value="3" class="treeOpClass">父子联动</label>
            <div id="menuTrees" class="ztree ztree-border"></div>
        </div>
    </div>
</form>

<?php $this->beginBlock('script'); ?>
    <script>
        $(function() {
            dataScopeChange();
            $("#data_scope_select").change(function (){
                dataScopeChange();
            });
            initTree()

        });

        function initTree(){
            var options = {
                id: "menuTrees",
                url: "<?=\yii\helpers\Url::toRoute('struct/tree')?>",
                ismult:true,
                childparent:false,
                expandLevel: 2,
            };
            $.tree.init(options);
            $('input.treeOpClass').on('ifChanged', function(obj){
                var type = $(this).val();
                var checked = obj.currentTarget.checked;
                if (type == 1) {
                    if (checked) {
                        $._tree.expandAll(true);
                    } else {
                        $._tree.expandAll(false);
                    }
                } else if (type == "2") {
                    if (checked) {
                        $._tree.checkAllNodes(true);
                        $.tree.zOnCheck();
                    } else {
                        $._tree.checkAllNodes(false);
                        $.tree.zOnCheck();
                    }
                } else if (type == "3") {
                    if (checked) {
                        $._tree.setting.check.chkboxType = { "Y": "ps", "N": "ps" };
                    } else {
                        $._tree.setting.check.chkboxType = { "Y": "", "N": "" };
                    }
                }
            })
        }
        function dataScopeChange(){
            var val = $("#data_scope_select").val()
            if(val=='8'){
                $("#customData").show()
            }else{
                $("#customData").hide()
            }
        }
        function submitHandler() {
            $.operate.save(aUrl, $('#form-add').serialize());
        }
    </script>
<?php $this->endBlock(); ?>

backend/modules/system/views/role/edit.php
<?php $this->context->layout = '/form';?>

<form class="form-horizontal m" id="form-edit">
    <input type="hidden" name="id" value="<?=$info['id']?>">
    <div class="form-group">
        <label class="col-sm-3 control-label is-required">角色名称：</label>
        <div class="col-sm-8">
            <input type="text" name="name" value="<?=$info['name']?>" class="form-control" placeholder="请输入角色名称" required autocomplete="off"/>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-3 control-label is-required">角色标识：</label>
        <div class="col-sm-8">
            <input type="text" name="rolekey" value="<?=$info['rolekey']?>" class="form-control" placeholder="请输入角色标识" required autocomplete="off"/>
            <span class="help-block m-b-none"><i class="fa fa-info-circle"></i> 角色唯一标识，使用3-20为字母、数字或‘_’组成</span>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-3 control-label is-required">显示顺序：</label>
        <div class="col-sm-8">
            <input type="number" name="listsort" class="form-control" placeholder="请输入显示顺序" autocomplete="off" value="<?=$info['listsort']?>"/>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-3 control-label is-required">角色状态：</label>
        <div class="col-sm-8">
            <label class="radio-box">
                <input type="radio" name="status" value="0" <?=$info['status']=='0'?'checked':''?>>停用
            </label>
            <label class="radio-box">
                <input type="radio" name="status" value="1" <?=$info['status']=='1'?'checked':''?>>启用
            </label>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-3 control-label ">备注：</label>
        <div class="col-sm-8">
            <textarea name="note" class="form-control" placeholder="请输入备注" rows="3"><?=$info['note']?></textarea>
        </div>
    </div>
</form>

<?php $this->beginBlock('script'); ?>
<script>
    function submitHandler() {
        if ($.validate.form()) {
            $.operate.save(oesUrl, $('#form-edit').serialize());
        }
    }
</script>
<?php $this->endBlock(); ?>

backend/modules/system/views/role/index.php
<div class="col-sm-12 search-collapse">
    <form id="role-form">
        <div class="select-list">
            <ul>
                <li>角色名称：<input type="text" name="like[name]"></li>
                <li>权限字符：<input type="text" name="like[rolekey]"></li>
                <li>组织状态：
                    <select name="where[status]">
                        <option value="">全部</option>
                        <option value="1">有效</option>
                        <option value="0">无效</option>
                    </select>
                <li>
                <li>
                    <a class="btn btn-primary btn-rounded btn-sm" onclick="$.table.search()"><i class="fa fa-search"></i> 搜索</a>
                    <a class="btn btn-warning btn-rounded btn-sm" onclick="$.form.reset()"><i class="fa fa-refresh"></i> 重置</a>
                </li>
            </ul>
        </div>
    </form>
</div>
<div class="btn-group-sm" id="toolbar" role="group">
    <a class="btn btn-success" onclick="$.operate.add(this)"><i class="fa fa-plus"></i> 新增</a>
    <a class="btn btn-primary single disabled" onclick="$.operate.edit('',this)"><i class="fa fa-edit"></i> 修改</a>
    <a class="btn btn-danger multiple disabled" onclick="$.operate.removeAll(this)"><i class="fa fa-trash"></i> 批量删除</a>
</div>
<div class="col-sm-12 select-table table-striped">
    <table id="bootstrap-table"></table>
</div>

<?php $this->beginBlock('script'); ?>
    <script>
        var root_id = "<?=$root_id?>";
        $(function () {
            var options = {
                modalName: "角色",
                sortName:'listsort',
                sortOrder:'asc',
                columns: [
                    {
                        checkbox: true,
                        formatter:function(value,row,index){
                            if(row.id == root_id) return {disabled : true};
                        }
                    },
                    {field: 'id', title: '角色ID', align: 'center', sortable: true},
                    {field: 'name', title: '角色名称'},
                    {field: 'rolekey', title: '权限字符'},
                    {field: 'listsort', title: '显示顺序',align: 'center', sortable: true},
                    {
                        title: '状态',
                        field: 'status',
                        align: 'center',
                        sortable: true,
                        formatter: function (value, row, index) {
                            return $.view.statusTools(row,true);
                        }
                    },
                    {field: 'create_time', title: '创建时间', align: 'center', sortable: true},
                    {field: 'update_time', title: '更新时间', align: 'center', sortable: true,visible: false},
                    {field: 'note', title: '备注',visible: false},
                    {
                        title: '操作',
                        align: 'center',
                        formatter: function(value, row, index) {
                            var actions = [];
                            actions.push('<a class="btn btn-success btn-xs" href="javascript:;" onclick="$.operate.edit(\'' + row.id + '\')"><i class="fa fa-edit"></i>编辑</a> ');
                            if(row.id != root_id){
                                actions.push('<a class="btn btn-danger btn-xs" href="javascript:;" onclick="$.operate.remove(\'' + row.id + '\')"><i class="fa fa-remove"></i>删除</a> ');
                                var more = [];

                                more.push("<a class='btn btn-default btn-xs' href='javascript:;' onclick='authMenu(" + row.id + ")'><i class='fa fa-check-square-o'></i>菜单权限</a> ");
                                more.push("<a class='btn btn-default btn-xs' href='javascript:;' onclick='dataScope(" + row.id + ")'><i class='fa fa-check-square-o'></i>数据权限</a> ");
                                actions.push('<a tabindex="0" class="btn btn-info btn-xs" role="button" data-placement="left" data-toggle="popover" data-html="true" data-trigger="hover" data-container="body" data-content="' + more.join('') + '"><i class="fa fa-chevron-circle-right"></i>更多操作</a>');
                            }
                            return actions.join('');
                        }
                    }
                ]
            };
            $.table.init(options);
        });
        /* 角色管理-菜单授权 */
        function authMenu(roleId) {
            var url = "<?=\yii\helpers\Url::toRoute('auth')?>";
            url=urlcreate(url,'role_id=' + roleId);
            $.modal.open("菜单授权", url);
        }
        /* 角色管理-数据范围 */
        function dataScope(roleId){
            var url = "<?=\yii\helpers\Url::toRoute('datascope')?>";
            url=urlcreate(url,'role_id=' + roleId);
            $.modal.open("分配数据权限", url);
        }
    </script>
<?php $this->endBlock(); ?>