backend/controllers/IndexController.php
<?php
// +----------------------------------------------------------------------
// | B5Yii2CMF V3.0 [快捷通用基础管理开发平台]
// +----------------------------------------------------------------------
// | Author: 冰舞 <357145480@qq.com>
// +----------------------------------------------------------------------
declare (strict_types=1);

namespace backend\controllers;

use backend\extend\BaseController;
use backend\extend\helpers\LoginAuthHelper;
use common\helpers\Functions;
use common\models\system\Menu;
use yii\helpers\Url;
use yii\web\Cookie;

class IndexController extends BaseController
{
    /**
     * 首页
     * @return string
     */
    public function actionIndex()
    {
        //是否开启横向菜单
        $topNav = false;
        $style = $this->request->cookies->getValue("nav-style","left");
        if($style == 'top'){
            $topNav = true;
        }

        $userInfo = LoginAuthHelper::adminLoginInfo();
        $menuTree = $this->getMenuListByLogin();
        if($topNav){
            return $this->renderPartial('indextop', ['user_info' => $userInfo, 'menuList' => $menuTree]);
        }
        $menuHtml = $this->menuToHtml($menuTree);
        return $this->renderPartial('', ['user_info' => $userInfo, 'menuHtml' => $menuHtml]);
    }

    /**
     * 主页
     * @return string
     */
    public function actionHome()
    {
        return $this->render();
    }

    /**
     * 主题
     * @return string
     */
    public function actionSkin(){
        return $this->render();
    }

    public function actionNavStyle(){
        $type = trim($this->request->get("type",'left'));
        $this->response->cookies->add(new Cookie(['name'=>'nav-style','value'=>$type]));
        return $this->success('切换成功');
    }

    /**
     * 下载文件
     * @return array|string
     */
    public function actionDownload(){
        $fileName = $this->request->get('fileName','');
        if(!$fileName) return $this->error('参数错误');
        header('location:'.Functions::getFileUrl($fileName));
    }
    /**
     * 根据登录session获取菜单
     * @return array
     */
    protected function getMenuListByLogin(): array
    {
        $menuTree = $menuList = [];
        $adminId = LoginAuthHelper::adminLoginInfo('info.id');
        if ($adminId) {
            $isAdmin = LoginAuthHelper::adminLoginInfo('info.is_admin');

            if ($isAdmin) {
                $menuList = Menu::find()->select(['id', 'type', 'name', 'url', 'parent_id', 'icon', 'is_refresh', 'target'])->where(['<>', 'type', 'F'])->andWhere(['status' => 1])->orderBy('parent_id asc,listsort asc,id asc')->asArray()->all();
            } else {
                $menuIdList = LoginAuthHelper::adminLoginInfo('menu');
                if ($menuIdList) {
                    //获取菜单
                    $menuList = Menu::find()->select(['id', 'type', 'name', 'url', 'parent_id', 'icon', 'is_refresh', 'target'])->where(['id' => $menuIdList])->andwhere(['<>', 'type', 'F'])->andWhere(['status' => 1])->orderBy('parent_id asc,listsort asc,id asc')->asArray()->all();
                }
            }
        }

        if ($menuList) {
            $menuTree = $this->getMenuTree($menuList);
        }
        return $menuTree?:[];
    }


    /**
     * 将菜单转为数形无限极
     * @param $list
     * @param int $pid
     * @param int $deep
     * @return array
     */
    protected function getMenuTree($list, $pid = 0, $deep = 0): array
    {
        $tree = [];
        foreach ($list as $key => $row) {
            if ($row['parent_id'] == $pid) {
                $row['deep'] = $deep;
                $url = $row['url'];
                if ($url && strpos($url, 'http') !== 0) {
                    $row['url'] = Url::toRoute($url);
                }
                unset($list[$key]);
                $row['child'] = $this->getMenuTree($list, $row['id'], $deep + 1);
                $tree[] = $row;
            }
        }
        return $tree;
    }

    /**
     * 将菜单树形转为html
     * @param $menus
     * @param int $deep
     * @return string
     */
    protected function menuToHtml($menus, $deep = 0): string
    {
        $html = '';
        if (is_array($menus)) {
            foreach ($menus as $t) {
                if ($t['deep'] == $deep) {
                    if ($t['type'] == 'C') {
                        $url = $t['url'];
                        if ($t['parent_id'] == 0) {
                            $html .= '<li><a class="' . ($t['target'] == '1' ? 'menuBlank' : 'menuItem') . '" href="' . $url . '" data-refresh="' . ($t['is_refresh'] ? 'true' : 'false') . '">' . ($t['icon'] ? '<i class="' . $t['icon'] . '"></i>' : '') . ' <span class="nav-label">' . $t['name'] . '</span></a></li>';
                        } else {
                            $html .= '<li><a class="' . ($t['target'] == '1' ? 'menuBlank' : 'menuItem') . '" href="' . $url . '" data-refresh="' . ($t['is_refresh'] ? 'true' : 'false') . '">' . $t['name'] . '</a></li>';
                        }

                    } else {
                        //实现最多三级菜单
                        if ($t['child'] && $deep < 3) {
                            $html .= '<li><a href="javascript:;">' . ($t['icon'] ? '<i class="' . $t['icon'] . '"></i>' : '') . ' <span class="nav-label">' . $t['name'] . '</span><span class="fa arrow"></span></a>';
                            $html .= '<ul class="nav ' . ($deep == 0 ? 'nav-second-level' : 'nav-third-level') . '">';
                            $html .= $this->menuToHtml($t['child'], $deep + 1);
                            $html = $html . "</ul></li>";
                        }
                    }
                }

            }
        }
        return $html;
    }


}

backend/views/layouts/footer.php
     <!-- bootstrap-table 表格插件 -->
    <script src="<?= yii\helpers\Url::to('@web/static/plugins/bootstrap-table/bootstrap-table.min.js') ?>"></script>
    <script src="<?= yii\helpers\Url::to('@web/static/plugins/bootstrap-table/locale/bootstrap-table-zh-CN.min.js') ?>"></script>
    <script src="<?= yii\helpers\Url::to('@web/static/plugins/bootstrap-table/extensions/mobile/bootstrap-table-mobile.min.js') ?>"></script>
     <?= $this->blocks['js_common']??''?>
    <!-- jquery-validate 表单验证插件 -->
    <script src="<?= yii\helpers\Url::to('@web/static/plugins/validate/jquery.validate.min.js') ?>"></script>
    <script src="<?= yii\helpers\Url::to('@web/static/plugins/validate/messages_zh.min.js') ?>"></script>
    <script src="<?= yii\helpers\Url::to('@web/static/plugins/validate/jquery.validate.extend.js') ?>"></script>

    <script src="<?= yii\helpers\Url::to('@web/static/plugins/blockUI/jquery.blockUI.js') ?>"></script>
    <script src="<?= yii\helpers\Url::to('@web/static/plugins/iCheck/icheck.min.js') ?>"></script>
    <script src="<?= yii\helpers\Url::to('@web/static/plugins/layui/layui.js') ?>"></script>
    <script src="<?= yii\helpers\Url::to('@web/static/js/iframe-ui.js') ?>"></script>
    <script src="<?= yii\helpers\Url::to('@web/static/js/common.js') ?>"></script>
    <?= $this->blocks['script_before']??''?>
    <?= $this->blocks['script']??''?>
    <?= $this->blocks['script_after']??''?>

backend/views/layouts/form.php
<?php
$this->beginPage();
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <?= $this->render('header')?>
</head>
<body class="white-bg">
<?php $this->beginBody() ?>
    <div class="wrapper wrapper-content animated fadeInRight ibox-content">
      <?= $content ?>
    </div>
    <?= $this->render('footer')?>
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

backend/views/layouts/full.php
<?php
$this->beginPage();
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <?= $this->render('header');?>
</head>
<body class="gray-bg">
<?php $this->beginBody() ?>
<?= $content ?>
<?= $this->render('footer')?>
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

backend/views/layouts/header.php
<?php $this->registerCsrfMetaTags() ?>
<title><?= $this->params['system_name']??'b5YiiCMF' ?></title>
<meta charset="charset">
<meta name="renderer" content="webkit">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
<link href="<?= yii\helpers\Url::to('@web/static/plugins/bootstrap/css/bootstrap.min.css') ?>" rel="stylesheet"/>
<link href="<?= yii\helpers\Url::to('@web/static/plugins/fontawesome/css/font-awesome.min.css') ?>" rel="stylesheet"/>
<link href="<?= yii\helpers\Url::to('@web/static/plugins/bootstrap-table/bootstrap-table.min.css') ?>" rel="stylesheet"/>
<?= $this->blocks['css_common']??''?>

<link href="<?= yii\helpers\Url::to('@web/static/plugins/layui/css/layui.css') ?>" rel="stylesheet">
<link href="<?= yii\helpers\Url::to('@web/static/plugins/animate/animate.css') ?>" rel="stylesheet"/>
<link href="<?= yii\helpers\Url::to('@web/static/css/style.css') ?>" rel="stylesheet"/>
<link href="<?= yii\helpers\Url::to('@web/static/css/iframe-ui.css') ?>" rel="stylesheet"/>
<script src="<?= yii\helpers\Url::to('@web/static/plugins/jquery/jquery-1.12.4.min.js') ?>"></script>
<script src="<?= yii\helpers\Url::to('@web/static/plugins/bootstrap/js/bootstrap.min.js') ?>"></script>
<script>

    var aUrl = "<?= \yii\helpers\Url::toRoute('')?>";
    var oasUrl="<?= \yii\helpers\Url::toRoute('add')?>";
    var oesUrl="<?= \yii\helpers\Url::toRoute('edit')?>";
    var upImgUrl="<?= \yii\helpers\Url::toRoute('/common/uploadimg')?>";
    var upFileUrl="<?= \yii\helpers\Url::toRoute('/common/uploadfile')?>";
    var bootUrl={
        url: "<?=\yii\helpers\Url::toRoute('index')?>",
        createUrl: decodeURIComponent("<?=\yii\helpers\Url::toRoute(['add','id'=>'%id%'])?>"),
        updateUrl: decodeURIComponent("<?=\yii\helpers\Url::toRoute(['edit','id'=>'%id%'])?>"),
        removeUrl: "<?=\yii\helpers\Url::toRoute('drop')?>",
        removeAllUrl: "<?=\yii\helpers\Url::toRoute('dropall')?>",
        clearCacheUrl: "<?=\yii\helpers\Url::toRoute('delcache')?>",
        cleanUrl: "<?=\yii\helpers\Url::toRoute('trash')?>",
        statusUrl:"<?=\yii\helpers\Url::toRoute('setstatus')?>",
        downUrl:"<?=\yii\helpers\Url::toRoute('/index/download')?>",
    }

</script>
<?php $this->head() ?>

backend/views/layouts/layout.php
<?php
$this->beginPage();
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <?= $this->render('header');?>
</head>
<body class="gray-bg">
<?php $this->beginBody() ?>
    <div class="container-div">
        <div class="row">
            <?= $content ?>
        </div>
    </div>
    <?= $this->render('footer')?>
    <?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

backend/views/layouts/none.php
<?= $content ?>